### ISSUE TITLE
using with webpack

### ISSUE THREAD

**Issue by tadjik1** [iliakan/bem-jade#2]
Hello. I am trying to use your mixin with webpack for something like that:

``` javascript
// component.js
import template from './template.jade';
...

// template.jade
+b.component
  +e.title Title
```

But unfortunately I don't understand how it's possible to use this library with [jade-loader](https://github.com/webpack/jade-loader). Could you help me please?
 That doesn't work

``` javascript
// webpack.config.js

var bem = require('bem-jade');
...
{
  test: /\.jade$/,
  loader: 'jade-loader',
  query: { bem: bem() }
}
```

**Comment by iliakan** [comment]
Please see the use case here: https://github.com/iliakan/javascript-nodejs/blob/90373d79c74e7d80e3ef723acb0998db7fb4f744/handlers/auth/client/authForm.js

**Comment by sofiia-hlyniana** [comment]
Hello, 

I've got the same question on using bem-jade with webpack. What configuration settings should be applied? Unfortunately the use case you've provided earlier was not helpful.

Thanks

**Comment by iliakan** [comment]
I'm not using any special settings. 
Only extension as here: https://github.com/iliakan/javascript-nodejs/blob/master/modules/lib/serverJade/index.js
